Resources:
  BalanceTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: ${self:custom.balanceTableName}
      AttributeDefinitions:
        - AttributeName: policyId
          AttributeType: S
        - AttributeName: typeDate
          AttributeType: S
      KeySchema:
        - AttributeName: policyId
          KeyType: HASH
        - AttributeName: typeDate
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
